### ISSUE TITLE
Upgrade to VW v8.0

### ISSUE THREAD

**Issue by trufanov-nok** [szilard/benchm-ml#23] opened 2015-08-14 17:03 UTC
It seems that VW 7.10 is under the current tests. Would be great if you update it with v.8.0:
https://github.com/JohnLangford/vowpal_wabbit/archive/8.0.zip
I don't think it'll change ROCs but would be interesting if there are any performance regressions happened.

**Comment by szilard** [comment] 2015-08-14 17:19
As I mentioned in the README "The linear models are not the primary focus of this study because of their not so great accuracy vs the more complex models (on this type of data)." Also "The main conclusion here is that it is trivial to train linear models even for n = 10M rows virtually in any of these tools on a single machine in a matter of seconds." and " the differences in memory efficiency and speed will start to really matter only for larger sizes and beyond the scope of this study."

However, feel free to run VW 7.10 (to reproduce my results) and 8.0 and let me know if significantly different.

**Comment by szilard** [comment] 2015-08-18 18:13
Closing this issue, feel free to reopen if you have any results.

**Closed as completed by szilard** 2015-08-18 18:13 UTC
